# Generated by Django 2.0.4 on 2018-04-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melon', '0002_auto_20180415_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
