# Generated by Django 2.0.4 on 2018-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melon', '0005_profstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profstatus',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
