# Generated by Django 2.0.4 on 2018-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melon', '0006_profstatus_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profstatus',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profstatus',
            name='uname',
            field=models.TextField(default=''),
        ),
    ]
