# Generated by Django 2.0.4 on 2018-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melon', '0007_auto_20180417_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='uname',
            field=models.TextField(default=''),
        ),
    ]
